sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.prod -t zirelion/docker-react .

script:
  - docker run -e CI=true zirelion/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-834505050674"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key